tasks:
  - init: mvn clean install
    command: java -jar ./target/spring-boot-in-docker.jar
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - gabrielbb.vscode-lombok
